parameters:
    kayue_wordpress.configuration.manager.class: Kayue\WordpressBundle\Wordpress\ConfigurationManager
    kayue_wordpress.security.authentication.provider.class: Kayue\WordpressBundle\Security\Authentication\Provider\WordpressProvider
    kayue_wordpress.security.authentication.listener.class: Kayue\WordpressBundle\Security\Firewall\WordpressListener
    kayue_wordpress.security.logout.handler.cookie_clearing.class: Kayue\WordpressBundle\Security\Http\Logout\WordpressCookieClearingLogoutHandler
    kayue_wordpress.security.cookie.service.class: Kayue\WordpressBundle\Security\Http\WordpressCookieService
    kayue_wordpress.security.encoder.phpass.class: Kayue\WordpressBundle\Security\Encoder\PhpassPasswordEncoder
    kayue_wordpress.table_prefix.subscriber.class: Kayue\WordpressBundle\Subscriber\TablePrefixSubscriber
    kayue_wordpress.doctrine.class: Kayue\WordpressBundle\Doctrine\ManagerRegistry
    kayue_wordpress.orm.entity_manager.class: Kayue\WordpressBundle\Doctrine\WordpressEntityManager

services:
    kayue_wordpress.configuration.manager:
        class: %kayue_wordpress.configuration.manager.class%
        arguments:
            - %kayue_wordpress.site_url%
            - %kayue_wordpress.cookie_path%
            - %kayue_wordpress.cookie_domain%
            - %kayue_wordpress.logged_in_key%
            - %kayue_wordpress.logged_in_salt%

    kayue_wordpress.security.authentication.provider:
        class: %kayue_wordpress.security.authentication.provider.class%
        public: false

    kayue_wordpress.security.authentication.listener:
        class: %kayue_wordpress.security.authentication.listener.class%
        arguments:
            - @security.context
            - @kayue_wordpress.security.cookie.service
            - @security.authentication.manager
            - @logger
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: security}

    kayue_wordpress.security.logout.handler.cookie_clearing:
        class: %kayue_wordpress.security.logout.handler.cookie_clearing.class%
        parent: security.logout.handler.cookie_clearing
        arguments:
            - @kayue_wordpress.configuration.manager

    kayue_wordpress.security.cookie.service:
        class: %kayue_wordpress.security.cookie.service.class%

    kayue_wordpress.security.encoder.phpass:
        class: %kayue_wordpress.security.encoder.phpass.class%

    kayue_wordpress.table_prefix.subscriber:
        class: %kayue_wordpress.table_prefix.subscriber.class%
        arguments:
            - %kayue_wordpress.table_prefix%
        tags:
            - {name: doctrine.event_subscriber}

    kayue_wordpress.doctrine:
        class: %kayue_wordpress.doctrine.class%
        arguments:
            - @service_container

    kayue_wordpress.orm.entity_manager.abstract:
        class:          %kayue_wordpress.orm.entity_manager.class%
        factory_class:  %kayue_wordpress.orm.entity_manager.class%
        factory_method: create
        abstract:       true

    kayue_wordpress.site.manager:
        class: Kayue\WordpressBundle\Wordpress\SiteManager
        scope: request
        arguments:
            - %kayue_wordpress.sites%
            - @request
            - @logger
