parameters:
#    kayue_wordpress.example.class: Kayue\WordpressBundle\Example

services:
#    kayue_wordpress.example:
#        class: %kayue_wordpress.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
