parameters:
    kayue_wordpress.security.authentication.provider.class: Kayue\WordpressBundle\Security\Authentication\Provider\WordpressProvider
    kayue_wordpress.security.authentication.listener.class: Kayue\WordpressBundle\Security\Firewall\WordpressListener

services:
    kayue_wordpress.security.authentication.provider:
        class: %kayue_wordpress.security.authentication.provider.class%
        public: false

    kayue_wordpress.security.authentication.listener:
        class: %kayue_wordpress.security.authentication.listener.class%
        arguments:
            - @security.context
            - @kayue_wordpress.security.cookie.service
            - @security.authentication.manager
            - @logger
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: security}

    kayue_wordpress.security.cookie.service:
        class: Kayue\WordpressBundle\Security\Http\WordpressCookieService
        arguments:
            - %kayue_wordpress.logged_in_key%
            - %kayue_wordpress.logged_in_salt%
            - null
            - null
            - @logger

    kayue_wordpress.security.encoder.phpass:
        class: Kayue\WordpressBundle\Security\Encoder\PhpassPasswordEncoder