parameters:
    kayue_wordpress.security.authentication.provider.class: Kayue\WordpressBundle\Security\Authentication\Provider\WordpressProvider
    kayue_wordpress.security.authentication.listener.class: Kayue\WordpressBundle\Security\Firewall\WordpressListener

services:
#    kayue_wordpress.example:
#        class: %kayue_wordpress.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kayue_wordpress.security.authentication.provider:
        class: %kayue_wordpress.security.authentication.provider.class%
        public: false

    kayue_wordpress.security.authentication.listener:
        class: %kayue_wordpress.security.authentication.listener.class%
        arguments:
            - @security.context
            - @kayue_wordpress.security.authentication.rememberme
            - @security.authentication.manager
            - @logger
            - @event_dispatcher
        tags:
            - {name: monolog.logger, channel: security}

    kayue_wordpress.security.authentication.rememberme:
        class: Kayue\WordpressBundle\Security\Http\WordpressRememberMeService
        arguments:
            - %kayue_wordpress.logged_in_key%
            - %kayue_wordpress.logged_in_salt%
            - null
            - null
            - @logger